name: Build Linux Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # 手动触发选项
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build

    # 5. 打包 Electron 应用 (构建 Linux Release 包)
      - name: Build Electron app
        run: npm run build:electron
        env:
          # 关键：禁用自动发布到外部商店
          PUBLISH: "never"
          # 设置虚拟 token 防止错误（可选）
          GH_TOKEN: "dummy-token"

    # 6. 上传构建产物 (可选但推荐)
      - uses: actions/upload-artifact@v4
        with:
          name: linux-electron-app
          path: |
            release/
            !release/**/*.yml  # 通常排除 electron-builder 的更新日志文件
          retention-days: 7  # 产物保留天数
